- name: Deploy Keycloak
  hosts: localhost
  gather_facts: no
  collections:
    - kubernetes.core
  vars_files:
    - vars.yaml
  tasks:  
  - name: Get Keycloak Admin
    kubernetes.core.k8s_info:
      kind: Secret
      namespace: "{{ deployment_namespace }}"
      name: keycloak-admin
    register: keycloak_admin_secret

  - name: Ensure Keycloak Admin secret is found
    ansible.builtin.assert:
      that:
        - keycloak_admin_secret.resources | length > 0
      fail_msg: "No Keycloak Admin secret found"
      success_msg: "Keycloak Admin secret found: {{ keycloak_admin_secret.resources[0].metadata.name }}"

  - name: Set Keycloak admin cred facts
    set_fact:
      keycloak_admin_username: "{{ keycloak_admin_secret.resources[0].data.username | b64decode }}"
      keycloak_admin_password: "{{ keycloak_admin_secret.resources[0].data.password | b64decode }}"

  - name: Configure master realm
    community.general.keycloak_realm:
      auth_keycloak_url: "https://sso.apps.cluster-2lrzw.2lrzw.sandbox2247.opentlc.com"
      auth_username: "{{ keycloak_admin_username }}"
      auth_password: "{{ keycloak_admin_password }}"
      auth_realm: "master"
      realm: "master"
      state: present
      display_name: "Keycloak Administration"
      display_name_html: '<div class="kc-logo-text"><span>Keycloak Administration</span></div>'
      admin_events_details_enabled: true
      admin_events_enabled: true
      brute_force_protected: true
      edit_username_allowed: false
      enabled: true
      events_enabled: true
      login_with_email_allowed: false
      registration_allowed: false
      remember_me: false
      reset_password_allowed: false
      verify_email: false
      ssl_required: "external"
    register: configure_master_realm_result

  - name: Configure Application Realm
    community.general.keycloak_realm:
      auth_keycloak_url: "https://sso.apps.cluster-2lrzw.2lrzw.sandbox2247.opentlc.com"
      auth_username: "{{ keycloak_admin_username }}"
      auth_password: "{{ keycloak_admin_password }}"
      auth_realm: "master"
      realm: "applications"
      state: present
      display_name: "Application Realm"
      display_name_html: '<div class="kc-logo-text"><span>Application Realm</span></div>'
      admin_events_details_enabled: true
      admin_events_enabled: true
      brute_force_protected: true
      edit_username_allowed: false
      enabled: true
      events_enabled: true
      login_with_email_allowed: false
      registration_allowed: false
      remember_me: false
      reset_password_allowed: false
      verify_email: false
      ssl_required: "external"
      organizations_enabled: false
    register: configure_application_realm_result
